/*
    * GENERAL NOTION
    * - naming interfaces with I prefix
    * - naming types with T prefix
    * - naming enum with E prefix
*/

export interface IDanPost {
    id: number,
    created_at: string,
    score: number,
    source: string,
    rating: string,
    image_width: number,
    image_height: number,
    tag_string: string,
    md5: string,
    file_ext: string,
    parent_id: number,
    has_children: boolean,
    tag_count_general: number,
    tag_count_artist: number,
    tag_count_character: number,
    tag_count_copyright: number,
    file_size: number,
    up_score: number,
    down_score: number,
    tag_count: number,
    updated_at: string,
    is_banned: boolean,
    has_active_children: boolean,
    uploader_name: string,
    has_large: boolean,
    children_ids: any,
    tag_string_general: string,
    tag_string_character: string,
    tag_string_copyright: string,
    tag_string_artist: string,
    tag_string_meta: string,
    file_url: string,
    large_file_url: string,
    preview_file_url: string
}

export type IDanTags =
    '1boy' |
    '1girl' |
    '2boys' |
    'after_sex' |
    'after_vaginal' |
    'ahoge' |
    'alcohol' |
    'all_fours' |
    'anal' |
    'anal_fingering' |
    'animal_ears' |
    'anus' |
    'arched_back' |
    'areolae' |
    'ass' |
    'ass_focus' |
    'ass_grab' |
    'back' |
    'back_cutout' |
    'bangs' |
    'bare_shoulders' |
    'barefoot' |
    'bent_over' |
    'big_hair' |
    'bikini' |
    'bikini_aside' |
    'black_panties' |
    'blonde_hair' |
    'blush' |
    'blush_stickers' |
    'bottomless' |
    'bra' |
    'bra_pull' |
    'breast_squeeze' |
    'breasts' |
    'breasts_apart' |
    'breasts_outside' |
    'bunny_ears' |
    'cat_ears' |
    'cat_tail' |
    'censored' |
    'choker' |
    'closed_mouth' |
    'condom' |
    'cowgirl_position' |
    'crossdressing' |
    'cum' |
    'cum_in_ass' |
    'cum_in_mouth' |
    'cum_in_pussy' |
    'cum_on_ass' |
    'cum_on_body' |
    'cum_on_breasts' |
    'cum_on_stomach' |
    'cum_on_tongue' |
    'cum_on_upper_body' |
    'cum_string' |
    'cumdrip' |
    'cup' |
    'dark_skin' |
    'deepthroat' |
    'doggystyle' |
    'dress_lift' |
    'drunk' |
    'erection' |
    'facial' |
    'fake_animal_ears' |
    'fang' |
    'feet' |
    'fellatio' |
    'fingering' |
    'fucked_silly' |
    'girl_on_top' |
    'glasses' |
    'gloves' |
    'groping' |
    'handjob' |
    'hands_on_another\'s_head' |
    'head_grab' |
    'heavy_breathing' |
    'hetero' |
    'holding' |
    'huge_ahoge' |
    'huge_breasts' |
    'invisible_man' |
    'invisible_penis' |
    'large_breasts' |
    'legs_together' |
    'licking_lips' |
    'lingerie' |
    'looking_at_viewer' |
    'looking_back' |
    'lying' |
    'maid' |
    'maid_headdress' |
    'male_focus' |
    'masturbation' |
    'medium_breasts' |
    'miniskirt' |
    'multiple_boys' |
    'multiple_girls' |
    'multiple_views' |
    'naughty_face' |
    'nipple_tweak' |
    'nipples' |
    'no_bra' |
    'no_panties' |
    'nude' |
    'oiled' |
    'on_back' |
    'on_bed' |
    'on_side' |
    'one_eye_closed' |
    'one_side_up' |
    'open_clothes' |
    'open_mouth' |
    'oral' |
    'otoko_no_ko' |
    'panties' |
    'panties_aside' |
    'pants_around_one_leg' |
    'pants_down' |
    'parted_lips' |
    'penis' |
    'pillow_grab' |
    'pleated_skirt' |
    'pointless_condom' |
    'ponytail' |
    'pov' |
    'precum' |
    'presenting' |
    'prostitution' |
    'pubic_hair' |
    'puffy_nipples' |
    'pussy' |
    'pussy_juice' |
    'rolling_eyes' |
    'saliva' |
    'sex' |
    'shelf_bra' |
    'sideboob' |
    'skirt' |
    'small_breasts' |
    'smile' |
    'solo' |
    'spread_legs' |
    'squatting' |
    'standing' |
    'suggestive_fluid' |
    'sweat' |
    'swimsuit' |
    'tail' |
    'tank_top' |
    'tears' |
    'teeth' |
    'tentacle_sex' |
    'tentacles' |
    'tentacles_under_clothes' |
    'testicles' |
    'thick_thighs' |
    'thighhighs' |
    'thighs' |
    'tongue' |
    'tongue_out' |
    'top-down_bottom-up' |
    'topless' |
    'torogao' |
    'uncensored' |
    'underwear' |
    'used_condom' |
    'vaginal' |
    'wedding_dress' |
    'wrist_cuffs' |
    'yaoi';

export interface IDanPostError {
    success: boolean,
    message: string
}

export type TDanRatings = 'explicit' | 'safe' | 'questionable';

export type TDanOrder = 'rank' | 'custom' | 'comment_bumped';
